### ISSUE TITLE
how to bulk update and bulk insert?

### ISSUE THREAD

**Issue by mgh2008** [sdrapkin/SecurityDriven.TinyORM#2]
how to bulk update and bulk insert? and what about performance? thaks

**Comment by sdrapkin** [comment]
For bulk updates and inserts you have multiple options, depending on your usecase and size of your data.

- You can use [Batched queries](https://github.com/sdrapkin/SecurityDriven.TinyORM/wiki/Batched-queries).
- You can use [Table-Valued-Parameters](https://github.com/sdrapkin/SecurityDriven.TinyORM/wiki/TVP-support) to push data to the database.
- You can use [Streaming](https://github.com/sdrapkin/SecurityDriven.TinyORM/wiki/Streaming) and push data into the `DataReader`.
- You can use [`SqlBulkCopy`](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlbulkcopy.aspx) (`ADO.NET`).
