### ISSUE TITLE
Database Migrations

### ISSUE THREAD

**Issue by tompazourek** [sdrapkin/SecurityDriven.TinyORM#3]
I'm thinking about moving away from EF and using TinyORM for a personal project of mine. Mostly for performance reasons, but also to have better control over everything and less magic happening.

EF as opposed to TinyORM also handles database migrations. I understand that this isn't really the focus of TinyORM, and that the mapping is supposed to be more dynamic and explicit. But if I'd be looking for some tool that would complement TinyORM and handle maintaining of database schema and database migrations, what would you recommend?

Do you have any personal experience with some of the tools out there, like the *Database projects in VS*, for example? I know that it's also possible to use EF migrations without using the rest of the full-featured framework, but I just wanted to pick your brain to see if you know about some db migrations library out there with similar principles as TinyORM (simple, fast, minimal), or your opinion on this matter in general.

Thanks for any feedback, sorry if this is a bit too off-topic.

**Comment by sdrapkin** [comment]
@tompazourek At work we have built a custom schema extractor - a codegen which brings TSQL schemas into c# land, and improves both the TSQL-writing-from-c# experience, and the correctness of dynamic TSQL as the database schema evolves.

**Comment by tompazourek** [comment]
@sdrapkin That sounds like an interesting approach, thanks for sharing. May I ask how you handle versioning of the database schema, and migrating to newer versions of the schema?

**Comment by sdrapkin** [comment]
@tompazourek Schema migrations are done as TSQL change scripts, checked in along with the c# code that leverages the schema changes, and versioned alongside with the code (ex. TFS). The scripts are either written manually (simple changes, such as add-a-new-column to a table), or generated with schema-diff'ing tools (more complex changes).

**Comment by tompazourek** [comment]
Thanks for your insights. Closing this now.
