### ISSUE TITLE
Stored procedure Execution

### ISSUE THREAD

**Issue by dev-thinks** [sdrapkin/SecurityDriven.TinyORM#4]
Is there anyway I can execute stored procedure and getting POCO objects as resultset?

I couldn't able to find it in Wiki.

please let me know. Thanks.

**Comment by sdrapkin** [comment]
@acclaimuser POCO-object results are covered in [quickstart](https://github.com/sdrapkin/SecurityDriven.TinyORM/wiki/Quick-start) - both static and anonymous.
Note the use of `ToObject<>` and `ToObjectArray<>` methods.

Stored procedures are executed the same way you would do it in T-SQL:
```csharp
await db.QueryAsync("EXEC MyStoredProc(param1, param2);")
```

**Comment by dev-thinks** [comment]
Thank you for pointing to the right place. I think the QueryInfo class is the one am looking for (passing SQL with parameters).

struggling to choose between Dapper and this one for the new assignment. !!!
Thanks again.
