### ISSUE TITLE
Compilation error for new Console Applications

### ISSUE THREAD

**Issue by eolamisan** [sdrapkin/SecurityDriven.TinyORM#5]
When the TinyOrm Nuget package is added to a new Console Application the following compilation errors appears:

`error CS1705: Assembly 'SecurityDriven.TinyORM' with identity 'SecurityDriven.TinyORM, Version=1.1.6701.26060, Culture=neutral, PublicKeyToken=e58a6d9408783005' uses 'System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'System.Threading.Tasks.Extensions' with identity 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

The workaround is to add the "'System.Threading.Tasks.Extensions" Nuget package.

**Comment by sdrapkin** [comment]
The [Nuget](https://www.nuget.org/packages/TinyORM/) for `v1.1.6701.26060` clearly states that there is a dependency on ` System.Threading.Tasks.Extensions (>= 4.3.0)`. If you have an older v4.1 `Tasks.Extensions` assembly, upgrading to a newer version fixes your compilation error.

**Comment by sdrapkin** [comment]
Updated Nuget [`v1.1.6848.28993`](https://www.nuget.org/packages/TinyORM/1.1.6848.28993) has been released. It references newer dependencies and fixes the mismatching versions. Thanks for reporting the issue.

**Comment by eolamisan** [comment]
Thank you!
