### ISSUE TITLE
Ready for .net core

### ISSUE THREAD

**Issue by IASamoylov** [sdrapkin/SecurityDriven.TinyORM#7]
Hi Stan! Are you going to add .net core support when Microsoft releases .net core 3.0?

**Comment by sdrapkin** [comment]
@IASamoylov Yes - hopefully even sooner than that. I plan for the next release to target NetStandard20 (ie. should work for both .NET full and NetCore). The only issue right now is [System.Data.SqlClient](https://www.nuget.org/packages/System.Data.SqlClient/) nuget. MS has broken batching in current version, but fixed it in 4.7.0-preview. I'm waiting for 4.7.0 to finally get released (ie. non-preview - I don't want to take a dependency on a preview package). All tests pass on 4.7.0-preview, so everything works.

If anyone notices that SqlClient 4.7.0 is released - ping me.

**Comment by khonoridez** [comment]
4.7.0 just released a few days ago. Regards
https://www.nuget.org/packages/System.Data.SqlClient/

**Comment by ghost** [comment]
@sdrapkin I've been running a build targeting 4.7.0-pre in production for a month plus, no issues as far as I can tell. If there is any way to help out with releasing a package update, please let me know. Thanks for your work on this!

**Comment by ghost** [comment]
@sdrapkin ping! :) ANything I can help with to get a .NET Core build out?

**Comment by sdrapkin** [comment]
Everyone, sorry for the lack of progress on this one and the delayed response - I've been away.

I'll get on it asap.

**Comment by sdrapkin** [comment]
[TinyORM.1.3.0.zip](https://github.com/sdrapkin/SecurityDriven.TinyORM/files/3763501/TinyORM.1.3.0.zip)

Can someone please sanity-test in their environments, to make sure it's ok to publish to Nuget?

**Comment by ghost** [comment]
@sdrapkin giving it a quick try now.

**Comment by ghost** [comment]
@sdrapkin all my persistence tests pass, I can run my app locally with the new package. .NET Core 3 app.

**Comment by sdrapkin** [comment]
Pushed to [Nuget](https://www.nuget.org/packages/TinyORM/).

**Comment by ghost** [comment]
Awesome, thanks @sdrapkin
