### ISSUE TITLE
Enum properties are not supported in CommandExtensions.GenerateParameter

### ISSUE THREAD

**Issue by dmitry-pavlov** [sdrapkin/SecurityDriven.TinyORM#8]
If entity class has property of some Enum type (e.g. MyNamesapce.MyEnumType) ORM raises the error: 

`System.Collections.Generic.KeyNotFoundException: The given key 'System.Nullable`1[MyNamesapce.MyEnumType]' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SecurityDriven.TinyORM.Extensions.CommandExtensions.GenerateParameter(String parameterName, Object parameterValue, Type parameterType)
   at SecurityDriven.TinyORM.Extensions.CommandExtensions.ProcessParameter(SqlCommand& command, SqlParameterCollection& sqlParameterCollection, String& name, Object& value, Type& type)
   at SecurityDriven.TinyORM.DbContext.CommitQueryBatchAsync(QueryBatch queryBatch, Int32 batchSize, CancellationToken cancellationToken, String callerMemberName, String callerFilePath, Int32 callerLineNumber)
`

**Comment by dmitry-pavlov** [comment]
Should there be some options for `DbContext` to set something like below?

```
var db = DbContext.Create(_connectionString);
db.MapEnumsAsInt = true; // should support nullable properties of course

```

**Comment by sdrapkin** [comment]
@dmitry-pavlov Can you please share the actual TinyORM code that raises the error? I'd like to understand whether you get it when you try to pass POCO with Enum-typed property in (ie. on the way into db), or you get a db-result and are trying to convert it into a POCO (ie. on the way out from db)..

Ex. given the following c# definitions, what would be a repro code for you?
```csharp
public enum Stage
{
	StageOne = 1,
	StageTwo = 2
}
public class Entity
{
	public string Name {get; set;}
	public Stage Progress { get; set;}
}
```

Given the above definitions, the following code works for me:
```csharp
var db = DbContext.Create(connString);

var result = await db.QueryAsync(
@$"SELECT [Name] = @name, [Progress] = @stage",
new { @name = "Stan", @stage = 2 }
).ConfigureAwait(false);

result[0].ToObject<Entity>().Dump();
```

**Comment by dmitry-pavlov** [comment]
I am trying to do bulk insert via TinyORM for performance (compared to EF Core). 

Note: `DbContext` is `TinyORM` thing, `XyzDbContext` is my `EF Core` DB context (used here only for helper methods - I just store there some constants needed)

Here some code to show how I use it:

```
        private static void InsertViaTinyOrm<TEntity>(Settings settings, ICollection<TEntity> entities)
            where TEntity : class
        {
            var chunks = ChunkBy(entities, settings.Database.BulkInsertChunkSize);

            var sql = GetBulkInsertQueryForEntityType(typeof(TEntity));

            var tasks = new List<Task>();

            foreach (var chunk in chunks)
            {
                var db = DbContext.Create(settings.Database.ConnectionString);
                
                var batch = QueryBatch.Create();

                foreach (var entity in chunk)
                {
                    batch.AddQuery(sql, entity);
                }
                
                tasks.Add(db.CommitQueryBatchAsync(batch));
            }

            Task.WaitAll(tasks.ToArray());
        }
```
Some helper methods to build SQL insert command based on my entity type: 
```
        private static List<List<T>> ChunkBy<T>(IEnumerable<T> source, int chunkSize)
        {
            return source?
                .Select((x, i) => new {Index = i, Value = x})
                .GroupBy(x => x.Index / chunkSize)
                .Select(x => x.Select(v => v.Value).ToList())
                .ToList();
        }

        private static string GetBulkInsertQueryForEntityType(Type type)
        {
            if (!XyzDbContext.TypeToTableMap.ContainsKey(type))
            {
                throw new NotSupportedException($"Define bulk insert query for {type.Name} entity.");
            }

            var tableName = XyzDbContext.TypeToTableMap[type];

            var propertyNames = type.GetProperties()
                .Select(property => property.Name)
                .Where(name => name != "Id")
                .ToArray();

            var columnNames = string.Join(",", propertyNames);

            var parameterNames = string.Join(",", propertyNames.Select(propertyName => $"@{propertyName}"));

            return $"insert into {XyzDbContext.Schema}.{tableName}({columnNames}) values({parameterNames});";
        }
```
TypeToTableMap is just a map for my EF  Core entity type to table name 

```
        public static Dictionary<Type, string> TypeToTableMap = new Dictionary<Type, string>
        {
            {typeof(Product), nameof(Products)},
            ...
        };
```
Hope that helps

**Comment by sdrapkin** [comment]
I think I have a repro for your error:

```csharp
async Task Main()
{
	var db = DbContext.Create(connString);

	var sql = @$"SELECT [Name] = @name, [Stage] = @stage";
	var parameters = new  { @name = "Stan", @stage = default(Stage)};
	
	var result = await db.QueryAsync(sql,parameters).ConfigureAwait(false);
	result.Dump();
}

public enum Stage
{
	StageOne = 1,
	StageTwo = 2
}
```

The above works fine, but if you change it to `default(Stage?)`, it throws what I think you're getting.

**Comment by sdrapkin** [comment]
Can you please try the following new TinyORM build:

[TinyORM.1.3.3.zip](https://github.com/sdrapkin/SecurityDriven.TinyORM/files/4741298/TinyORM.1.3.3.zip)

**Comment by dmitry-pavlov** [comment]
Yeap, `v1.3.3` works fine with enums. Thanks @sdrapkin 

When are you going to publish `v1.3.3` to NuGet? 

P.S. I have also added one additional not critical improvement request here #9

**Comment by dmitry-pavlov** [comment]
Please feel free to close the issue once you publish `v1.3.3` to `NuGet`. Thanks!
