### ISSUE TITLE
Improvement Request: Map DateTime to DbType.DateTime2 instead of DbType DateTime

### ISSUE THREAD

**Issue by dmitry-pavlov** [sdrapkin/SecurityDriven.TinyORM#9]
Now `TinyORM` seems to map .NET `DateTime` type to `DbType DateTime`. I propose to use `DbType.DateTime2` instead to avoid getting the error below when default date time value (which is `0001/01/01`) is used. 

`SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.`

Error reason is explained [here](https://dapper-tutorial.net/knowledge-base/19423880/inserting-data-with-dapper-with-datetime2-throws-sqldatetime-overflow-exception) and [here](https://stackoverflow.com/a/1334193/804385).

**Comment by sdrapkin** [comment]
@dmitry-pavlov TinyORM has always automatically used `DateTime2` DbType when processing `DateTime` .NET type.

Running the following code should illustrate this:

```csharp
var sql = @$"SELECT [DT] = @dt INTO #x; SELECT * from #x; EXEC tempdb..sp_columns '#x'; ";
var parameters = new { @dt = default(DateTime) };

var result = await db.QueryMultipleAsync(sql, parameters).ConfigureAwait(false);
result.Dump(); // assuming you run it in LinqPad
```

**Comment by dmitry-pavlov** [comment]
I have got the above exception when passed entity with DateTime property (also NOT NULL on DB side) which was never set. It seems on .NET side in this case it is considered as `0001-01-01 00:00:00` and this code raises the error: 

```
                var batch = QueryBatch.Create();
                foreach (var entity in chunk)
                {
                    batch.AddQuery(sql, entity);
                }
                db.CommitQueryBatchAsync(batch));
```

**Comment by sdrapkin** [comment]
```TSQL
BEGIN TRY
	CREATE TABLE #x(DT DATETIME);

	DECLARE @dt DATETIME2 = '0001-01-01';
	SELECT @dt;

	INSERT INTO #x(DT) VALUES(@dt);
	SELECT * FROM #x;
	DROP TABLE #x;
END TRY

BEGIN CATCH
	SELECT
		ERROR_NUMBER() AS ErrorNumber,
		ERROR_STATE() AS ErrorState,
		ERROR_SEVERITY() AS ErrorSeverity,
		ERROR_PROCEDURE() AS ErrorProcedure,
		ERROR_LINE() AS ErrorLine,
		ERROR_MESSAGE() AS ErrorMessage;
	DROP TABLE #x;
END CATCH
```

The above T-SQL produces the following error:

> The conversion of a datetime2 data type to a datetime data type resulted in an out-of-range value.

This is no different than the following scenario of trying to insert an `INT` into ` TINYINT` column:

```TSQL
BEGIN TRY
	CREATE TABLE #x(VAL SMALLINT);

	DECLARE @val INT = -123456789;
	SELECT @val;

	INSERT INTO #x(VAL) VALUES(@val);
	SELECT * FROM #x;
	DROP TABLE #x;
END TRY

BEGIN CATCH
	SELECT
		ERROR_NUMBER() AS ErrorNumber,
		ERROR_STATE() AS ErrorState,
		ERROR_SEVERITY() AS ErrorSeverity,
		ERROR_PROCEDURE() AS ErrorProcedure,
		ERROR_LINE() AS ErrorLine,
		ERROR_MESSAGE() AS ErrorMessage;
	DROP TABLE #x;
END CATCH
```

...which produces the following error:
> Arithmetic overflow error for data type smallint, value = -123456789.

In both of these cases, TinyORM does not auto-adjust the value of the passed-in data to the min-value of the in-DB-data-type. The current logic avoids guessing the intent of the caller/developer, lets the DB throw an error, and expects the caller/developer to adjust based on in-DB constraints.
